### ISSUE TITLE
Mods dont show up

### ISSUE THREAD

**Issue by BuGo14** [Nuclearistt/TEKLauncher#10]
I downloaded like 10mods on tek launcher started the game and in the main manu was only 2mods showing up, none were downloading in bottom of the screen... any fix or tip please? also the mods are showing up in the mods file in ark files...

**Comment by Nuclearistt** [comment]
The launcher's role here is solely downloading the mods, which it did, everything else is up to other apps/tools. I might have a look at it if you post screenshots in Discord as we have more general support there
