### ISSUE TITLE
can't open apps in windows 11

### ISSUE THREAD

**Issue by phucuonq** [Nuclearistt/TEKLauncher#12]
can't open apps in windows 11
can't open app in windows 11, doesn't show any error, when i click run app nothing happens

**Comment by Nuclearistt** [comment]
The launcher is confirmed to run on Win11, make sure you have the latest .NET 6 Desktop Runtime installed

**Comment by BHNAM12** [comment]
I'm having the same problem. I downloaded NET6 or whatever its called and still not working. when I double click nothing happen.
