### ISSUE TITLE
Launcher not opening 

### ISSUE THREAD

**Issue by Veryfunnyguy** [Nuclearistt/TEKLauncher#13]
That's it it's just not opening

**Comment by Veryfunnyguy** [comment]
I've got all requirements it is not opening still

**Comment by Nuclearistt** [comment]
Most likely you have a startup crash due to corrupted Settings.json, go to %appdata%\TEK Launcher and delete it there

**Comment by yeezusman** [comment]
i think i have this issue too, i'll launch the tek launcher application and my pc asks if i want to run the file. i click yes, and nothing happens, not even an error message or anything like that. quite literally nothing. i tried to do the solution you listed, but i cannot find the file that i am supposed to delete. i cannot find a settings.json file, although there is a settings.bin file that i did try deleting and nothing changed. i even tried deleting the entire folder and still nothing. i dont know if this is just my computer, as it worked yesterday once and then occurred after i attempted to install an update for the base game.

**Comment by Nuclearistt** [comment]
Do you also have the **latest** .NET 6 Desktop Runtime installed? Does it create DomainException.txt in the %appdata%\TEK Launcher folder?

**Comment by yeezusman** [comment]
It does not create DomainException.txt. I did not see any change in terms of file creation or deletion.

**Comment by sgtbane** [comment]
Had the same issue when upgrading from v8.3.71.1 that was working fine. Would not launch, no error messages. Rolling back to the version before .NET6 was implimented and it worked fine again.

If it is the same case with you, check to see if any of the [Releases](https://github.com/Nuclearistt/TEKLauncher/releases) prior to migrating to .NET6 still works. If they do you know its a .NET6 issue, not likely an issue with the launcher.

The launcher appears to download v6.0.0 of the .NET 6.0 runtime and install it, but it was still not working. The one [supplied from Microsoft](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime) is at v6.0.4 right now, and installing that manually fixed the issue for me.

**Comment by yeezusman** [comment]
I downloaded an older version and it seems to launch just fine. Newer version still does not launch, so it's likely that its a .NET6 issue.

**Comment by marcospdsf** [comment]
Just installed the x86 version from the provided link and it worked fine.
