### ISSUE TITLE
Epic Games v/ Controller not working

### ISSUE THREAD

**Issue by thijsi123** [Nuclearistt/TEKLauncher#16]
I have the epic games version of ark and all the mods etc... works great but there's one problem, My gamepad doesn't work in the modded ark via TEKlauncher any idea why? (it works on the normal version)

**Comment by Nuclearistt** [comment]
The launcher has nothing to do with that and that's described in #faq in the Discord server

**Comment by thijsi123** [comment]
Oh thanks, I'll check it out.
