### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by bitsbb01** [Nuclearistt/TEKLauncher#17]
I love the launcher, but 1 thing I've noticed is that it will create the mods folder in the root of the game, and will copy the basics of the mod to the mod folder in contents, however the unpacked which is in the mods/root has to be copied over afterwards, can it do this automatically?

**Comment by Nuclearistt** [comment]
I don't get it. The Mods folder in game root is only for compressed mod files that are downloaded from Steam servers, basically the alternative to Steam\steamapps\workshop\content\346110. Then during unpacking process those files are read, decompressed and written to the mod's folder in ShooterGame\Content\Mods, and .mod file is composed and written to that folder as well. That's all that needs to be done for a mod to be installed correctly, so I don't understand what do you want to copy, from where and why
