### ISSUE TITLE
DLC's

### ISSUE THREAD

**Issue by magicxavi** [Nuclearistt/TEKLauncher#19]
For some unknown reason, i can't download any DLC.
What i tried:
1. Checked if spacewar installed
2. Tried validating game files
3. Tried to use VPN
It always says "can't download manifest"

**Comment by Nuclearistt** [comment]
Steam added extra ownership check on its content servers recently, I'm working on a workaround for that

**Comment by magicxavi** [comment]
Thanks for the info and your work!

пн, 16 мая 2022 г., 00:11 Nuclearist ***@***.***>:

**Comment by magicxavi** [comment]
> Steam added extra ownership check on its content servers recently, I'm working on a workaround for that

Man, that was a fast fix from you, thanks again!
