### ISSUE TITLE
Hosting dedicated server with mods

### ISSUE THREAD

**Issue by spider312** [Nuclearistt/TEKLauncher#2]
Hi, i'm hosting an Ark server with mods, and a friend using tek launcher has message "No pirate ARK servers found on this adress" when trying to add this server to his list. I can't find any documentation on how to host such a server

Where can i found a doc on how to perform this please ?

**Comment by Nuclearistt** [comment]
In [Arkouda Discord](https://discord.gg/9C3aSFc) in #tutorials channel. You will need to register with the Launchers role there to access it first

**Comment by spider312** [comment]
Thanks :)
