### ISSUE TITLE
my launcher lates alot to open

### ISSUE THREAD

**Issue by piettrogabriel123** [Nuclearistt/TEKLauncher#21]
i have a issue with tek launcher, i click to open and he wont opens im here waiting till 30 minutes and nothing yet

**Comment by Nuclearistt** [comment]
Do you have the latest .NET 6 Desktop Runtime installed?

**Comment by piettrogabriel123** [comment]
yes but how do i use it

**Comment by piettrogabriel123** [comment]
i downloaded it on my pc but it wont changed

**Comment by Nuclearistt** [comment]
Do you have DomainException.txt in %appdata%\TEK Launcher? If so, send it here

**Comment by piettrogabriel123** [comment]
ok wait i will see

**Comment by piettrogabriel123** [comment]
no

**Comment by piettrogabriel123** [comment]
i dont have this file

**Comment by Nuclearistt** [comment]
Then, either it fails to create that file, which I haven't seen happening to anyone so far, or you don't have the .NET 6 Desktop Runtime set up correctly or it's an old version

**Comment by piettrogabriel123** [comment]
ok what is the recent version of .NET

**Comment by Nuclearistt** [comment]
You can see it on its website

**Comment by piettrogabriel123** [comment]
what site exacly

**Comment by piettrogabriel123** [comment]
OH wait i saw a version 6.0 is it?

**Comment by piettrogabriel123** [comment]
EEK IT OPENED

**Comment by piettrogabriel123** [comment]
thx and... sorry for make you lost time
