### ISSUE TITLE
failed to read file. invalid Json Token. line: 1 ch: 1

### ISSUE THREAD

**Issue by piettrogabriel123** [Nuclearistt/TEKLauncher#22]
PLEASE HELP ME REEEEEEEEEEEEE

**Comment by Nuclearistt** [comment]
Where exactly do you get that? Screenshot if possible

**Comment by piettrogabriel123** [comment]
ok i will send

**Comment by piettrogabriel123** [comment]
well when i press "play" it appaears the error

**Comment by Nuclearistt** [comment]
Everything that happens after pressing that button is the matter of game process, not launcher
