### ISSUE TITLE
latest version teklauncher not opening

### ISSUE THREAD

**Issue by Sartajiboi** [Nuclearistt/TEKLauncher#25]
my teklauncher is not opening and when i give it permission to change stuff in my drive it says i need to install .net but i already have it installed and now its not opening at all no message no anything . im using a hp envy laptop with a cpu being amd ryzeon 7 and amd radeon graphics card. please fix this bug i finnaly got a big hardrive i can play ark with im disapointed

**Comment by Sartajiboi** [comment]
btw thank you for making this. i played before and im so happy i can play ark without paying. were a poor family soo yeah. keep up the good work.

**Comment by Nuclearistt** [comment]
I cannot fix this bug because 1) This is(was?) .NET's built-in message, not mine 2) Most likely that's not bug at all. Check if you have DomainException.txt in %appdata%\TEK Launcher, if you do send it here, otherwise you don't have the needed version of runtime, it must be the latest of .NET **6 Desktop** Runtime

**Comment by Sartajiboi** [comment]
One more thing. How do you access %appdata%

**Comment by Sartajiboi** [comment]
What do you mean by send it here,

**Comment by Sartajiboi** [comment]
And i dont have DomainException.txt and i have latest .NET runtime
installed, so what should i do?

**Comment by Nuclearistt** [comment]
Seeing that you claim you don't have the exception file I assume you already found the appdata folder. In which case the issue is about runtime and it's out of my scope

**Comment by Sartajiboi** [comment]
Have a great day.
