### ISSUE TITLE
wi fi problem with tek launcher

### ISSUE THREAD

**Issue by Stefkethenoob** [Nuclearistt/TEKLauncher#26]
why is my wi fi so much slower when i update something in teklauncher?
Like it goes to 10 kb per second.

**Comment by Stefkethenoob** [comment]
and also when i update ark is always gonna say download or update time out

**Comment by Stefkethenoob** [comment]
And also manifest also dont want to download like failed to download manifest

**Comment by Nuclearistt** [comment]
Looks like your connection is just too slow and/or unstable to handle 20 download threads (that number can be changed in launcher settings), nothing really related to the launcher itself
