### ISSUE TITLE
Failed to download manifest

### ISSUE THREAD

**Issue by cristihot** [Nuclearistt/TEKLauncher#28]
Hi there and first of all thanks for this great software.

After today last update 9.1.76.3 when im trying to download an dlc (or just updating it) it just keep saying failed to download manifest.
Can you please have a look?

Many thanks
![Screenshot 2022-06-13 120250](https://user-images.githubusercontent.com/6179200/173318862-e97117d5-0901-403c-ad83-59fbdb626781.png)
!

**Comment by Nuclearistt** [comment]
It occasionally happens to some people,I assume  either Steam is rate-limiting my bot that does that request for you, or the bot itself is getting too many requests. Though some people solved it by restarting the launcher or retrying few times, so might as well be launcher's UDP client getting stalled or something

**Comment by HunterYT0** [comment]
It is not fixing please help
I cannot download DLCs

**Comment by Nuclearistt** [comment]
The issue has nothing to do with download cache, so you just got lucky

**Comment by autumn0w0** [comment]
try using a vpn 
or if ur using one then close it 
it worked for me

**Comment by FlashVN010** [comment]
It's a bit late but I think I found the solution. Try switch to another steam download region guys.
If you don't know how to do it watch this video at 0:41
https://www.youtube.com/watch?v=NEkiKQZJ8Js

**Comment by Nuclearistt** [comment]
It's completely unrelated. TEK Launcher doesn't use Steam app settings

**Comment by allyxmx-stack** [comment]
hey, i think i found the solution, i think....
so i kinda used an old version of the launcher (9.4.85). It worked for me, but i dont know if it works for anyone else.
Hope it works for anyone else
