### ISSUE TITLE
Restarting downloads instead of resuming

### ISSUE THREAD

**Issue by ElGrandeKobra** [Nuclearistt/TEKLauncher#30]
TEK Launcher no longer resumes dlc downloads after pausing them, but instead, just restarts the download process from 0.

**Comment by Nuclearistt** [comment]
That's not restart, it does resume, you may see that total progress value decreases every time. The current progress value for paused download is considered zero after resuming, it's done for the sake of not breaking ETA calculations but I might change that logic at some point later

**Comment by ElGrandeKobra** [comment]
Ohhh, yea didn't notice, and another problem is that some downloads go up more than 100%, it reached 115% once when I was downloading ext.
