### ISSUE TITLE
jeu en cours d'execution

### ISSUE THREAD

**Issue by Raynox063** [Nuclearistt/TEKLauncher#32]
je ne peux plus installer de mods de DLC ou faire de mise a jour car le launcher TEK me dit que le jeu est en cours d'execution alors qu'il est fermer donc je ne peux plus rien faire vous pouvez m'aider ?
![Uploading Capture d’écran (3).png…]()

**Comment by Nuclearistt** [comment]
It's a game bug when it doesn't shutdown properly and keeps a background process running. You may either find it in task manager and terminate or reboot PC to get rid of it

**Comment by Raynox063** [comment]
je ne trouve pas le processus en arrière plan et quand je redémarre mon PC rien ne change je peux plus rien installer :(
