### ISSUE TITLE
Unable to download new DLCs

### ISSUE THREAD

**Issue by TheCrazyLunatic8** [Nuclearistt/TEKLauncher#33]
Ever since Fjordur has been released, ARK from the Tek Launcher is acting very weird and buggy. Genesis 2 and Fjordur won't even load, and I can't seem to reinstall Fjordur because it's unable to get the latest manifests. Is there any way to fix this? I've tried installing the latest version as well as restarting my system multiple times.

Haven't played the game in over a week just because of these issues. I would at least like a response as to why the Tek Launcher doesn't work.

![image](https://user-images.githubusercontent.com/70371808/174492403-266a86ca-827c-4187-ba54-b323c4ee2653.png)
![image](https://user-images.githubusercontent.com/70371808/174492418-841e2a23-f291-4ae9-a3ba-3419f3b3ce60.png)
![image](https://user-images.githubusercontent.com/70371808/174492836-2be9a17c-f3b9-43f4-8f4d-f351a4b78f4c.png)

**Comment by Nuclearistt** [comment]
ARK from Tek Launcher = ARK from Steam. Your screenshots with launcher's windows imply it does work. As of the issue with manifests, I need to test few things with users who experience the issue to be able to do anything about it. Contact me in Discord, it needs a more real-time method of communication

**Comment by aternativ** [comment]
where can i find your discord? i have the same problem

**Comment by Nuclearistt** [comment]
Literally in the beginning of readme. But don't expect me to be active right now, it's night here

**Comment by aternativ** [comment]
Oh, i'm blind, thank you. We seem to be around the same time zone cause it's also night here so i'll leave a message in support when i can

**Comment by TheCrazyLunatic8** [comment]
> ARK from Tek Launcher = ARK from Steam. Your screenshots with launcher's windows imply it does work. As of the issue with manifests, I need to test few things with users who experience the issue to be able to do anything about it. Contact me in Discord, it needs a more real-time method of communication

Very well. I will do that as soon as I can.

**Comment by TheCrazyLunatic8** [comment]
Alright. It seems to be working now. But it still occurs occasionally. I have joined your Discord. We can talk more about the problem there.
