### ISSUE TITLE
je en cours d'éxecution

### ISSUE THREAD

**Issue by Raynox063** [Nuclearistt/TEKLauncher#34]
rebonjour j'ai toujours le même problème pour les téléchargement a cause du jeu en cours d'éxecution car je ne trouve pas de processus en arrière plan que je peux terminer et quand je redémarre mon PC le problème persiste

**Comment by Nuclearistt** [comment]
As you may see in the code, the check that triggers that message looks for any process named ShooterGame.exe, so it may not necessarily be the game but you have a process with that name somewhere in your system
