### ISSUE TITLE
(Proton) Error when trying to download DLC

### ISSUE THREAD

**Issue by Star-X555** [Nuclearistt/TEKLauncher#35]
Yeah yeah I know, "can't possibly support Linux", but I figure this might be important.

When selecting any non-free DLC to download, it tries to load the manifest, and then pops up with the error below.
![teklauncher_fatal_error](https://user-images.githubusercontent.com/41553900/175220691-5a55bcee-7675-4c8b-bbe5-83dc4ff028d1.png)

Probably is entirely Linux's fault, but if there's a chance it can be fixed I'd be grateful for any help, as I can't find any other means of obtaining the DLC files atm.

Also, sorry for not posting in Discord.  It's utterly impossible for me to use it now that virtually every discord server requires cell phone authentication with no workarounds left.

**Comment by Nuclearistt** [comment]
1. What does it have to do with Linux considering that it's entirely a Windows app?
2. TEKnology Hub only requires email verification for users and even that as a requirement for enabling community server, same applies to most other servers I'm member of
3. Try deleting ARK\Manifests folder

**Comment by Star-X555** [comment]
> 1. What does it have to do with Linux considering that it's entirely a Windows app?
I'm running it through Wine/Proton, that's why.  Hence why I'm blaming Linux for it, cause I've no idea if the problem is actually the program or a bug in Wine/Proton.
> 
>     2. TEKnology Hub only requires email verification for users and even that as a requirement for enabling community server, same applies to most other servers I'm member of
Not in my experience.  Discord refuses to allow me to post unless I give them a cell phone number with texting capabilities.  I've tried to find workarounds, but they just aren't reliable enough to bother with.
> 
>     3. Try deleting ARK\Manifests folder
Nope, didn't work.  Still gives me the same error.

**Comment by Nuclearistt** [comment]
Ok, then if anything is left in that folder after getting error, send it here so I can examine the file and figure out what exactly is wrong

**Comment by Star-X555** [comment]
https://drive.google.com/file/d/1rpgMLRLVNxKPWpWUAKsX5DiYRVKz9X2P/view?usp=sharing

There's the file.
