### ISSUE TITLE
Failed to download manifest

### ISSUE THREAD

**Issue by CRLS26** [Nuclearistt/TEKLauncher#37]
i can't update the game or download any dlc ( Failed to Download Manifest )

![Captura de tela 2022-07-03 130352](https://user-images.githubusercontent.com/108019500/177047759-5fc49256-479b-4fb7-bb57-854d4c3fe3ff.png)

**Comment by Nuclearistt** [comment]
If you still have the issue come to Discord so we can test few things with more convenient way of communication

**Comment by Manidarean5** [comment]
me too, what the discord?
![image](https://user-images.githubusercontent.com/108998523/178119598-c5bbf991-1017-4a47-af0f-acd791cc524a.png)
