### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by MaulerWolf09** [Nuclearistt/TEKLauncher#39]
The downloaded .exe from here is a past version and when you run the update within it, it won't open.

**Comment by Nuclearistt** [comment]
From "here" is where? And why not straight download the latest version?

**Comment by MaulerWolf09** [comment]
I've downloaded the latest version and it claims to be version 8.3.71.1. So
I tried updating it from the launcher and it updates, creates a new exe and
then doesn't launch

**Comment by Nuclearistt** [comment]
Where exactly did you download the "latest" version? Doesn't sound like any of my sources

**Comment by MaulerWolf09** [comment]
https://github.com/Nuclearistt/TEKLauncher/releases/tag/v9.3.80.0

Straight from this pages assets, I downloaded the new launcher exe. I did
it from my phone and it launched but said it was v8...., and when I
downloaded it on pc it doesn't launch.

**Comment by Nuclearistt** [comment]
The file from there cannot be any other version than 9.3.80
If it doesn't run then 99% sure it's missing .NET 6 Desktop Runtime, which is mentioned on top of readme and is such case in my opinion it makes absolutely no sense to create an issue

**Comment by MaulerWolf09** [comment]
I've already installed the runtime twiceSent from my Galaxy
-------- Original message --------From: Nuclearist ***@***.***> Date: 8/10/22  11:16 am  (GMT+10:00) To: Nuclearistt/TEKLauncher ***@***.***> Cc: MaulerWolf09 ***@***.***>, Author ***@***.***> Subject: Re: [Nuclearistt/TEKLauncher] Fails to launch (Issue #39) 
The file from there cannot be any other version than 9.3.80
If it doesn't run then 99% sure it's missing .NET 6 Desktop Runtime, which is mentioned on top of readme and is such case in my opinion it makes absolutely no sense to create an issue

**Comment by Nuclearistt** [comment]
Check %appdata%\TEK Launcher folder, if there's DomainException.txt send it here, otherwise it's still some runtime-related issue that takes place before launcher's code gets to run

**Comment by MaulerWolf09** [comment]
Much to my disgrace, some reason my pc was downloading x86 automatically.
It works, very sorry for the trouble, but thanks for the help. Keep up  the
great work man, we all appreciate you.
