### ISSUE TITLE
TEK Launcher won't run

### ISSUE THREAD

**Issue by BlackieBo0** [Nuclearistt/TEKLauncher#4]
Hello, I have recently downloaded the update and when I try to run the launcher It will just not open. I've deleted it, installed it again and nothing works! Please help.

**Comment by nirooj56** [comment]
It happened to me as well. Turns out you need to download and install .NET 6 in order for TEK Launcher to run. Search, Download and install it from Microsoft website.

**Comment by BlackieBo0** [comment]
Thank you! I could get it to run!

**Comment by Biganti1** [comment]
My game, isn't Running i has install the .NET 6, and nothing happens

**Comment by Shadowmeph** [comment]
updated after reading about the .net 6 installed everything up and running , I fired up the launcher loaded up my game save and well none of my mods were installed anymore so I lost 60 % of everything all my work weeks of work gone hehe 
thats ok will have to rebuild everything from scratch also it was my own fault for not checking after the update and before I launched the game

**Comment by Desudesaru** [comment]
why does my launcher stop working when the validation and download thing reaches 100%? it says its 100% yet its still says "downloading files". I've tried uninstalling and installing it and I still get the same problem. Please do help me if you know a way on how to fix this problem, ty.
