### ISSUE TITLE
TEKLauncher won't run

### ISSUE THREAD

**Issue by BlackieBo0** [Nuclearistt/TEKLauncher#41]
Hello, I need some help- TEKLauncher is not running on my device, I have uninstalled and installed it multiple times but when I try to open it it will simply just not run- I even uninstalled the .NET 6 program and reinstalled it again and it still doesn't run, I don't know what may be the issue.

**Comment by Nuclearistt** [comment]
Was it .NET \***6**\* \***Desktop**\* Runtime \***x64**\*?
