### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by unknown3121** [Nuclearistt/TEKLauncher#43]
game keeps crashing once i open a map
i have to validate genesis map but still crash next time i open my game need a better solution
[LastCrash.txt](https://github.com/Nuclearistt/TEKLauncher/files/9963218/LastCrash.txt)

**Comment by Nuclearistt** [comment]
Game behaviour including crashes is not the scope of TEK Launcher, its job is merely downloading and launching the game, nothing afterwards
