### ISSUE TITLE
Steam API Initialization Failed 

### ISSUE THREAD

**Issue by ElonMusksGas** [Nuclearistt/TEKLauncher#48]
When ever I attempt to press play and start the game I keep Getting the "Steam API Initialization Failed" pop up. 
Any help is very much appreciated, please and thank you very much.

**Comment by Salivating11ama** [comment]
I also have this message, even more interesting and problematic is that after launching the program (Tek Launcher) I get this error on all steam games, some becoming unplayable and others displaying a message on startup. reinstalling steam and the games fixes the issue but launching Tek Launcher again will cause the problem to come back.

**Comment by ElonMusksGas** [comment]
So I was just over looking a glaring issue and I've dealt with it before I just forgot to try it. I had to whitelist the program in my anti virus

**Comment by magistrjan** [comment]
Disable administrator startup in the launcher settings. Play -> Administrator Rights
