### ISSUE TITLE
Space War runs in Steam - Ark crashing

### ISSUE THREAD

**Issue by lems24** [Nuclearistt/TEKLauncher#53]
Have been using the Tek Launcher for awhile now and haven't had any issues. Now, when I press "Play" in the Launcher, SpaceWars runs through Steam and now Ark has a fatal error. I installed .NET 7 Desktop Runtime that's in the notes on GitHub. I'm still receiving the same error. Just seeing if anyone else has had problems or knows what I can do to change this?

**Comment by lems24** [comment]
![ARK Fatal Error](https://user-images.githubusercontent.com/22061721/226203786-40fbb49b-c396-40d9-867f-add9ac9978a9.png)

**Comment by Nuclearistt** [comment]
Game crashes are not topic of the launcher.
