### ISSUE TITLE
failed to download manifest

### ISSUE THREAD

**Issue by fkzp** [Nuclearistt/TEKLauncher#54]
![image](https://user-images.githubusercontent.com/101929400/230773573-8ebf3b24-965b-487a-a541-38c51e587f3b.png)
I can't download MOD

**Comment by rigbydontsleep** [comment]
did u find a solution

**Comment by rigbydontsleep** [comment]
> i get the same error, i have the last tek launcher version someone get a fix it???

sadly no but im still trying lets just hope they fix it before i loose my mind

**Comment by bitsbb01** [comment]
my Tek Launcher started doing this as well, tried restarting system, signing out of steam and then sighn back in and still not working.
