### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Medran02** [Nuclearistt/TEKLauncher#56]
This message came up when trying to download a DLC
![Captura de pantalla (118)](https://github.com/Nuclearistt/TEKLauncher/assets/135402182/20e1a5de-39e5-41a0-8b62-a538ce63def9)

**Comment by Medran02** [comment]
Does anyone know how to fix it?

**Comment by llbranco** [comment]
Make sure you have enough disk space, keep in mind that Ark is one of the games that consumes the most disk space (~400GB with all DLC)
