### ISSUE TITLE
Faild To Get Manifest

### ISSUE THREAD

**Issue by unknown3121** [Nuclearistt/TEKLauncher#62]
![Screenshot (5)](https://github.com/Nuclearistt/TEKLauncher/assets/117583964/88f704be-1c59-4daf-b34c-6829df932864)

**Comment by Nuclearistt** [comment]
There is an issue with the Steam account used by my bot that gets those request codes, it's going to take some time to resolve it, so for now you have to wait

**Comment by unknown3121** [comment]
what if i change my steam account?

**Comment by Nuclearistt** [comment]
That won't change account on my server and the launcher simply wouldn't use yours anyway since it would need your account credentials for that

**Comment by Nuclearistt** [comment]
Fixed now

**Comment by unknown3121** [comment]
thanks
