### ISSUE TITLE
Save My Charecter

### ISSUE THREAD

**Issue by unknown3121** [Nuclearistt/TEKLauncher#63]
its not an issue more like a question witch is how can I keep my online character I mean every time I delete tek launcher my online character goes missing when i redownload the game I cannot find that character is there any way i can keep one of my character for lifetime?

**Comment by llbranco** [comment]
If you are playing online, your character's data is saved on the server (check with your server how long it leaves the character saved, generally 7~90 days depending on the server) this also depends on whether the server will continue to exist when you return playing.

If you are playing offline, go to the folder where you have ark installed and navigate to
ARK\ShooterGame\Saved
copy these folders, save in a safe location... when you reinstall, return your save to the same path and you will have everything the same...

It even works to copy saves to another computer
