### ISSUE TITLE
BatlleEye Continue installing

### ISSUE THREAD

**Issue by ShahziabMasood** [Nuclearistt/TEKLauncher#65]
When Ever I launch Game with some mods like structure plus and ark supreme. on loading screen battle eye installation pop pops out and ask to install battle eye if I click on install it will remain same it will ask to install battle eye again and again

**Comment by Nuclearistt** [comment]
Not a launcher related issue, seen that happening to some people but don't remember if and how they solved it, anyway it has to do with either game or mods installation
