### ISSUE TITLE
كل ما احاول ادخل

### ISSUE THREAD

**Issue by luckeybram** [Nuclearistt/TEKLauncher#67]
كل ما احاول ادخل يظهر لي 
![Error 08_02_2024 03_53_49 م](https://github.com/Nuclearistt/TEKLauncher/assets/159451575/8a347efc-c243-40ff-a111-5c48d4a1453d)

**Comment by luckeybram** [comment]
ارجو الرد

**Comment by Nuclearistt** [comment]
The message tells you what to do
