### ISSUE TITLE
How to fully uninstall tek launcher?

### ISSUE THREAD

**Issue by CatyWolf** [Nuclearistt/TEKLauncher#68]
I had a problem and files are missing... I can't update which gives an installation error and when valid it says files are missing, I want to uninstall and install to see if it can be resolved

**Comment by Nuclearistt** [comment]
Wait what are you going to resolve? Missing game files? Let validation do it, that's exactly what it is for. The launcher is just a single exe (besides settings file in appdata but that doesn't really matter) so uninstalling is not a term that applies to it, simpy deleting that exe would be enough if you wish although that doesn't really make any sense
