### ISSUE TITLE
tek launcher wont launch

### ISSUE THREAD

**Issue by CobraLovesArk** [Nuclearistt/TEKLauncher#7]
I tried to download the new tek launcher update, when i did it crashed and it wont relaunch.
I uninstalled and reinstalled the launcher but the same thing happens everytime, and none of the dlc and game updates save, im resorting to DODO launcher for now. :(

**Comment by Nuclearistt** [comment]
If it actually crashes, there should be DomainException.txt file in %appdata%\TEK Launcher, and I'd need to see what you have in there. Or it may also be possible that you just didn't download the .NET 6 desktop runtime

**Comment by dadadadaddddaad** [comment]
i have the same issue,i can t open the tek launcher and i reinstalled it,i reinstalled ark either and still it does not open
