### ISSUE TITLE
donk

### ISSUE THREAD

**Issue by donkk555** [Nuclearistt/TEKLauncher#70]
что делать пишет  ошибка directx как это пофиксить есл в лаунчере это нельзя сделать

**Comment by Nuclearistt** [comment]
Самому скачать его, установщик находится первым же запросом в любом поисковике

**Comment by donkk555** [comment]
а можеж пожалуйста какой диретекс скачать и если можно сыллку

**Comment by Nuclearistt** [comment]
https://www.microsoft.com/ru-ru/download/details.aspx?id=35

**Comment by Nuclearistt** [comment]
https://www.microsoft.com/ru-ru/download/details.aspx?id=35
