### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by riteshrhkr** [Nuclearistt/TEKLauncher#74]
The window size of launcher is more then screen, due to that some bottom and right side of launcher not visible. If you can make launcher window maximum size = computer screen size  and also  make window can be resigned that's grate. 
    

Except that Thank you so much for this awesome launcher.

**Comment by Nuclearistt** [comment]
I think what actually happened is your screen being smaller than **minimum** window size (1350x720), UI isn't particularly optimized for small screens so had to make it this to ensure everything fits. Either way, the is going to be rewritten from scratch for next version
