### ISSUE TITLE
Game from Xbox PC Game pass

### ISSUE THREAD

**Issue by Manidarean5** [Nuclearistt/TEKLauncher#81]
TekLauncher says that the game files doesn´t exist.

**Comment by Nuclearistt** [comment]
Which is kinda true, the launcher can work only with Steam edition of the game, the Xbox one has entirely different structure both file- and code-wise

**Comment by Manidarean5** [comment]
It isn't a console, its the game downloaded from Xbox Windows App for PC with the PC game pass

**Comment by Nuclearistt** [comment]
Nevertheless it's still Xbox edition of the game, not Steam
