### ISSUE TITLE
Failed to download manifest 

### ISSUE THREAD

**Issue by riteshrhkr** [Nuclearistt/TEKLauncher#82]
In Tek Launcher (for Ark Survival Evolved) I often see that when I try to download the game or any map I see error like this

![Screenshot (57)](https://github.com/user-attachments/assets/598da871-2524-4e7f-bd5a-5f85cb5e57f7)

Please can you fix this issue. Also the same issue I see in Tek Launcher for Ascended.

Thanks!

**Comment by Nuclearistt** [comment]
This occurs when Steam server doesn't return proper manifest IDs, so basically their side issue

**Comment by Spo0dsE** [comment]
i'm having the same issue. do you know what could be causing this on my end?

thanks!

**Comment by Nuclearistt** [comment]
Screenshot it, it might not be the same as you think
