### ISSUE TITLE
Tek Launcher Epic Games cannot find server - battle eye not running 

### ISSUE THREAD

**Issue by ITDev93** [Nuclearistt/TEKLauncher#83]
If i run Ark with Epic, it starts battle eye...
Using Tek however starts normal game...

I cannot see my private nitrado server, even though my server has battle eye off...
And i use tek to install mods...

But can you help me with the battle eye part?
Can I perhaps pass parameters to start Ark with battle eye on tek launcher?

**Comment by Nuclearistt** [comment]
No, BattlEye is not supported, it doesn't allow my code injections. As of your server, you don't see it because it doesn't have TEK Wrapper installed on it, and you won't be able to do that on Nitrado

**Comment by ITDev93** [comment]
makes sense, i guess i have no option but to buy ark from steam...
thanks a lot...
