### ISSUE TITLE
CPU usage by 70-80%

### ISSUE THREAD

**Issue by Skufen0k** [Nuclearistt/TEKLauncher#86]
Is it normal that when loading Ark Survival Ascended, the CPU load is 70-80%? (CPU ryzen 5 7500f)

**Comment by Nuclearistt** [comment]
Game questions are up to game developers, not here. Unless the CPU usage comes from the launcher process

**Comment by Nuclearistt** [comment]
It is fine, it's not only downloading but also decrypting and decompressing data in up to 20 threads in parallel, though there is room for improvement, new downloader made for next version is much lighter on resources
