### ISSUE TITLE
how i play non dedicated with my friends?

### ISSUE THREAD

**Issue by diegogit03** [Nuclearistt/TEKLauncher#90]
this is my question?

**Comment by bajic07** [comment]
i was wondering too, we both have tek launchers ark and we dont know how to play together

**Comment by Nuclearistt** [comment]
One person creates the session and invites others via Steam overlay, they must be in the game as well

**Comment by diegogit03** [comment]
Yeah i forget reply it, it have bugs but works fine when you join
